**Capítulo 10 – NumPy para Computação Numérica**

_Este notebook contém todos os códigos de exemplo e soluções para os exercícios do Capítulo 10._

<table align="left">
  <td>
    <a href="https://colab.research.google.com/drive/1UEc5hntE2I14BRW-HNhRii5nTDhACLJc?authuser=1#scrollTo=3SNbtY_UXdQp" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

# Configuração

Este projeto requer Python 3.11 ou superior:

In [ ]:
import sys

assert sys.version_info >= (3, 11)

In [ ]:
!python --version

Python 3.11.13


Criando Arrays

In [1]:
import numpy as np

# Criando arrays a partir de listas Python
lista_simples = [1, 2, 3, 4, 5]
array_simples = np.array(lista_simples)
print(f"Array simples: {array_simples}")
print(f"Tipo do array: {type(array_simples)}")
print(f"Tipo dos elementos do array (dtype): {array_simples.dtype}")
# Saída:
# Array simples: [1 2 3 4 5]
# Tipo do array: <class 'numpy.ndarray'>
# Tipo dos elementos do array (dtype): int64

Array simples: [1 2 3 4 5]
Tipo do array: <class 'numpy.ndarray'>
Tipo dos elementos do array (dtype): int64


In [2]:
# Criando array 2D (matriz) a partir de uma lista de listas
lista_de_listas = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(lista_de_listas)
print(f"\nArray 2D:\n{array_2d}")
print(f"Dimensões do array (shape): {array_2d.shape}") # (linhas, colunas)
print(f"Número de dimensões (ndim): {array_2d.ndim}")
# Saída:
# Array 2D:
# [[1 2 3]
#  [4 5 6]]
# Dimensões do array (shape): (2, 3)
# Número de dimensões (ndim): 2


Array 2D:
[[1 2 3]
 [4 5 6]]
Dimensões do array (shape): (2, 3)
Número de dimensões (ndim): 2


Funções para Criar Arrays Comuns

In [3]:
# Array de zeros
array_zeros = np.zeros((3, 4)) # 3 linhas, 4 colunas de zeros
print(f"\nArray de zeros:\n{array_zeros}")

# Array de uns
array_uns = np.ones((2, 3)) # 2 linhas, 3 colunas de uns
print(f"\nArray de uns:\n{array_uns}")

# Array com valores em um determinado intervalo (similar a range())
array_intervalo = np.arange(0, 10, 2) # Início, Fim (exclusivo), Passo
print(f"\nArray de intervalo: {array_intervalo}")

# Array com espaçamento linear (linspace)
# Cria N números igualmente espaçados entre dois limites (inclusive)
array_linspace = np.linspace(0, 10, 5) # 5 números entre 0 e 10
print(f"\nArray linspace: {array_linspace}")

# Array com números aleatórios
array_aleatorio_inteiro = np.random.randint(0, 10, size=(2, 3)) # Inteiros entre 0 (inc) e 10 (exc), shape 2x3
print(f"\nArray aleatório de inteiros:\n{array_aleatorio_inteiro}")

array_aleatorio_float = np.random.rand(3, 2) # Floats entre 0 e 1, shape 3x2
print(f"\nArray aleatório de floats:\n{array_aleatorio_float}")


Array de zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array de uns:
[[1. 1. 1.]
 [1. 1. 1.]]

Array de intervalo: [0 2 4 6 8]

Array linspace: [ 0.   2.5  5.   7.5 10. ]

Array aleatório de inteiros:
[[9 6 6]
 [4 3 6]]

Array aleatório de floats:
[[0.51948437 0.37011616]
 [0.76734266 0.307988  ]
 [0.25508233 0.74032385]]


Indexação e Fatiamento (Slicing) de Arrays

In [4]:
array_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# Acessando elementos (indexação começa em 0)
print(f"\nPrimeiro elemento: {array_1d[0]}")     # Saída: Primeiro elemento: 10
print(f"Terceiro elemento: {array_1d[2]}")     # Saída: Terceiro elemento: 30
print(f"Último elemento: {array_1d[-1]}")      # Saída: Último elemento: 70

# Fatiamento (slicing)
print(f"Do índice 1 ao 4 (exclusivo): {array_1d[1:4]}") # Saída: Do índice 1 ao 4 (exclusivo): [20 30 40]
print(f"Do início ao índice 3 (exclusivo): {array_1d[:4]}") # Saída: Do início ao índice 3 (exclusivo): [10 20 30 40]
print(f"Do índice 4 ao final: {array_1d[4:]}")   # Saída: Do índice 4 ao final: [50 60 70]
print(f"Todos os elementos: {array_1d[:]}")    # Saída: Todos os elementos: [10 20 30 40 50 60 70]


Primeiro elemento: 10
Terceiro elemento: 30
Último elemento: 70
Do índice 1 ao 4 (exclusivo): [20 30 40]
Do início ao índice 3 (exclusivo): [10 20 30 40]
Do índice 4 ao final: [50 60 70]
Todos os elementos: [10 20 30 40 50 60 70]


Indexação em Arrays 2D (Matrizes)

In [5]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(f"\nMatriz:\n{matriz}")

# Acessando um elemento específico
print(f"Elemento na linha 0, coluna 1: {matriz[0, 1]}") # Saída: Elemento na linha 0, coluna 1: 2

# Acessando uma linha inteira
print(f"Primeira linha: {matriz[0, :]}") # Saída: Primeira linha: [1 2 3]
print(f"Segunda linha: {matriz[1]}")     # Também funciona para linhas inteiras
# Saída: Segunda linha: [4 5 6]

# Acessando uma coluna inteira
print(f"Segunda coluna: {matriz[:, 1]}") # Saída: Segunda coluna: [2 5 8]

# Fatiamento em 2D
print(f"Sub-matriz (linhas 0 a 1, colunas 1 a 2):\n{matriz[0:2, 1:3]}")
# Saída:
# Sub-matriz (linhas 0 a 1, colunas 1 a 2):
# [[2 3]
#  [5 6]]


Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento na linha 0, coluna 1: 2
Primeira linha: [1 2 3]
Segunda linha: [4 5 6]
Segunda coluna: [2 5 8]
Sub-matriz (linhas 0 a 1, colunas 1 a 2):
[[2 3]
 [5 6]]


Indexação Booleana (Muito Poderoso para Dados!)

In [6]:
dados = np.array([10, 15, 20, 25, 30, 35, 40])

# Selecionar elementos maiores que 20
condicao = dados > 20
print(f"\nCondição (booleana): {condicao}")
# Saída: Condição (booleana): [False False False  True  True  True  True]

elementos_filtrados = dados[condicao] # ou dados[dados > 20]
print(f"Elementos maiores que 20: {elementos_filtrados}")
# Saída: Elementos maiores que 20: [25 30 35 40]

# Selecionar elementos pares
pares = dados[dados % 2 == 0]
print(f"Elementos pares: {pares}")
# Saída: Elementos pares: [10 20 30 40]


Condição (booleana): [False False False  True  True  True  True]
Elementos maiores que 20: [25 30 35 40]
Elementos pares: [10 20 30 40]


Operações Vetorizadas (Ganho de Performance)

In [7]:
array_a = np.array([1, 2, 3, 4])
array_b = np.array([5, 6, 7, 8])

# Adição elemento por elemento
soma = array_a + array_b
print(f"\nSoma de arrays: {soma}") # Saída: Soma de arrays: [ 6  8 10 12]

# Multiplicação escalar
multiplicacao_escalar = array_a * 2
print(f"Multiplicação escalar: {multiplicacao_escalar}") # Saída: Multiplicação escalar: [2 4 6 8]

# Potência elemento por elemento
potencia = array_a ** 2
print(f"Potência de array: {potencia}") # Saída: Potência de array: [ 1  4  9 16]

# Operações de comparação também são vetorizadas
comparacao = array_a > array_b
print(f"Comparação (A > B): {comparacao}") # Saída: Comparação (A > B): [False False False False]


Soma de arrays: [ 6  8 10 12]
Multiplicação escalar: [2 4 6 8]
Potência de array: [ 1  4  9 16]
Comparação (A > B): [False False False False]


Funções Matemáticas com NumPy

In [8]:
dados = np.array([1, 4, 9, 16, 25])

# Raiz quadrada
raiz_quadrada = np.sqrt(dados)
print(f"\nRaiz quadrada: {raiz_quadrada}") # Saída: Raiz quadrada: [1. 2. 3. 4. 5.]

# Logaritmo natural
logaritmo = np.log(dados)
print(f"Logaritmo natural: {logaritmo}")
# Saída: Logaritmo natural: [0.         1.38629436 2.19722458 2.77258872 3.21887582]

# Soma de todos os elementos
soma_total = np.sum(dados)
print(f"Soma total: {soma_total}") # Saída: Soma total: 55

# Média
media = np.mean(dados)
print(f"Média: {media}") # Saída: Média: 11.0

# Desvio padrão
desvio_padrao = np.std(dados)
print(f"Desvio padrão: {desvio_padrao:.2f}") # Saída: Desvio padrão: 8.57

# Máximo e Mínimo
valor_maximo = np.max(dados)
valor_minimo = np.min(dados)
print(f"Valor máximo: {valor_maximo}, Valor mínimo: {valor_minimo}")
# Saída: Valor máximo: 25, Valor mínimo: 1

# Transpor uma matriz
matriz_original = np.array([[1, 2], [3, 4]])
matriz_transposta = matriz_original.T # Ou np.transpose(matriz_original)
print(f"\nMatriz original:\n{matriz_original}")
print(f"Matriz transposta:\n{matriz_transposta}")
# Saída:
# Matriz original:
# [[1 2]
#  [3 4]]

# Matriz transposta:
# [[1 3]
#  [2 4]]


Raiz quadrada: [1. 2. 3. 4. 5.]
Logaritmo natural: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Soma total: 55
Média: 11.0
Desvio padrão: 8.65
Valor máximo: 25, Valor mínimo: 1

Matriz original:
[[1 2]
 [3 4]]
Matriz transposta:
[[1 3]
 [2 4]]


**Exercícios do Capítulo 10**

1.	Crie um array NumPy chamado idades a partir da lista [22, 25, 30, 28, 22, 35].
o	Imprima o array e seu dtype.
o	Qual é a idade média?
o	Qual é a idade máxima e mínima?
o	Quantas pessoas têm 22 anos? (Dica: use indexação booleana e np.sum()).
2.	Crie um array 2D (matriz) de 3x3 preenchido com zeros, chamado matriz_zeros.
o	Preencha o elemento na posição (1,1) (linha 1, coluna 1) com o valor 99.
o	Imprima a matriz resultante.
3.	Crie dois arrays: temperaturas_celsius = np.array([0, 10, 20, 30, 40]) e temperaturas_fahrenheit_esperado = np.array([32, 50, 68, 86, 104]).
o	Converta temperaturas_celsius para Fahrenheit usando a fórmula F = 1.8 C * 32.
o	Verifique se o seu array convertido é igual ao temperaturas_fahrenheit_esperado usando um operador de comparação e imprima o resultado.
4.	Crie um array NumPy de 50 números aleatórios inteiros entre 1 e 100.
o	Encontre e imprima quantos desses números são maiores que 50.
o	Calcule a soma de todos os números neste array.
5.	Dada a matriz A = np.array([[1, 2], [3, 4]]) e a matriz B = np.array([[5, 6], [7, 8]]).
o	Calcule a multiplicação elemento a elemento (A * B).
o	Calcule a multiplicação de matrizes (produto escalar) usando np.dot(A, B) ou A @ B.
o	Imprima ambos os resultados.

Uau! Você acaba de dar um passo gigantesco em direção à manipulação de dados com o NumPy. A habilidade de trabalhar com arrays e realizar operações vetorizadas é a base para quase tudo em Data Science.
No próximo capítulo, vamos mergulhar no Pandas, a biblioteca que leva a manipulação de dados a um nível ainda mais alto, permitindo que você trabalhe com tabelas de dados de forma intuitiva e poderosa. É a ferramenta que realmente fará seus dados "falarem"!

Respostas dos Exercícios do Capítulo 10:

In [9]:
# Exercícios 1:

import numpy as np

# Crie um array NumPy chamado idades
idades = np.array([22, 25, 30, 28, 22, 35])

print("1. Array de idades:", idades)
print("Tipo de dados (dtype):", idades.dtype)

# Idade média
media = np.mean(idades)
print("Idade média:", media)

# Idade máxima e mínima
print("Idade máxima:", np.max(idades))
print("Idade mínima:", np.min(idades))

# Quantas pessoas têm 22 anos?
quantidade_22 = np.sum(idades == 22)
print("Quantidade de pessoas com 22 anos:", quantidade_22)

1. Array de idades: [22 25 30 28 22 35]
Tipo de dados (dtype): int64
Idade média: 27.0
Idade máxima: 35
Idade mínima: 22
Quantidade de pessoas com 22 anos: 2


In [10]:
# Exercício 2:

# Crie uma matriz 3x3 preenchida com zeros
matriz_zeros = np.zeros((3, 3), dtype=int)

# Preencha a posição (1,1) com 99 (linha 1, coluna 1)
matriz_zeros[1, 1] = 99

print("\n2. Matriz com valor 99 na posição (1,1):\n", matriz_zeros)


2. Matriz com valor 99 na posição (1,1):
 [[ 0  0  0]
 [ 0 99  0]
 [ 0  0  0]]


In [11]:
# Exercício 3:

# Arrays de temperaturas
temperaturas_celsius = np.array([0, 10, 20, 30, 40])
temperaturas_fahrenheit_esperado = np.array([32, 50, 68, 86, 104])

# Conversão correta: F = C * 1.8 + 32
temperaturas_fahrenheit_calculado = temperaturas_celsius * 1.8 + 32

# Comparação
iguais = np.array_equal(temperaturas_fahrenheit_calculado, temperaturas_fahrenheit_esperado)

print("\n3. Temperaturas convertidas:", temperaturas_fahrenheit_calculado)
print("As temperaturas batem com o esperado?", iguais)


3. Temperaturas convertidas: [ 32.  50.  68.  86. 104.]
As temperaturas batem com o esperado? True


In [12]:
# Exercício 4:

# Crie um array com 50 números inteiros aleatórios entre 1 e 100
numeros = np.random.randint(1, 101, size=50)

print("\n4. Array de números aleatórios:\n", numeros)

# Quantos são maiores que 50?
maiores_que_50 = np.sum(numeros > 50)
print("Quantidade de números > 50:", maiores_que_50)

# Soma total
print("Soma de todos os números:", np.sum(numeros))


4. Array de números aleatórios:
 [  3  87  53  32  80  71   1  79  84  69  50   9  17  49  39  69  65  32
   2  41  68  99  29  53  82  43   1  82  33  94 100  49  76  76  69  44
  99  20  20  90  42  20  23  29   1  40  94  69  83  69]
Quantidade de números > 50: 25
Soma de todos os números: 2629


In [13]:
# Exercício 5:

# Matrizes A e B
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicação elemento a elemento
produto_elemento = A * B

# Produto escalar (multiplicação de matrizes)
produto_escalar = np.dot(A, B)  # ou A @ B

print("\n5. Multiplicação elemento a elemento:\n", produto_elemento)
print("Produto escalar (multiplicação de matrizes):\n", produto_escalar)


5. Multiplicação elemento a elemento:
 [[ 5 12]
 [21 32]]
Produto escalar (multiplicação de matrizes):
 [[19 22]
 [43 50]]
